name: ruuvitag-measurement-api

services:
  server:
    build: .
    restart: unless-stopped
    networks:
      - ruuvitag
    volumes:
      - "$PWD/config.toml:/etc/ruuvitag-measurement-api/config.toml"
    ports:
      - "8180:8180"

networks:
  ruuvitag:
    name: ruuvitag
    external: true
